services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: taxbilim_postgres
    environment:
      POSTGRES_DB: taxbilim_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - taxbilim_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build: .
    container_name: taxbilim_backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/taxbilim_db
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 5000
      NODE_ENV: development
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - taxbilim_network
    restart: unless-stopped
    command: sh -c "./start.sh"

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: taxbilim_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - taxbilim_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  taxbilim_network:
    driver: bridge 