import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ToastProvider} from '@/components/providers/toaster-provider'
import {ConfettiProvider} from '@/components/providers/confetti-provider'
import localfont from 'next/font/local';
import Providers from "@/app/providers";
import ErrorBoundary from "@/components/ErrorBoundary";

const inter = Inter({subsets: ['latin']})
const gilroy = localfont({
  src: [
    {
      path: '../../public/fonts/Gilroy-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Gilroy-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Gilroy-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Gilroy-Semibold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Gilroy-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Gilroy-Extrabold.ttf',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Gilroy-RegularItalic.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../../public/fonts/Gilroy-MediumItalic.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../../public/fonts/Gilroy-BoldItalic.ttf',
      weight: '700',
      style: 'italic',
    },
  ],
  display: 'swap',
  variable: '--font-gilroy', // optional, if you want to reference via CSS var
});

export const metadata: Metadata = {
  title: 'TaxBilim',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {

  return (
    // <ClerkProvider>
    <html lang="en">
    <body className={gilroy.className}>
    <ErrorBoundary>
      <ConfettiProvider/>
      <ToastProvider/>
      <Providers>{children}</Providers>
    </ErrorBoundary>
    </body>
    </html>
    // </ClerkProvider>
  )
}
